### ISSUE TITLE
`batch` emits empty batches.

### ISSUE THREAD

**Issue by jjttjj** [bsless/more.async#1]
Hi, thanks for the library!

Your `batch` function emits batches even when they are empty. That is, if no values came in over the batch time period, it will put an empty collection on the out chan. In my usage I usually only want values emitted if the batch is not empty. Just wondering if this is intentional or an oversight.

For what it's worth, manifold's `batch` function doesn't emit empty values.

Another minor unrelated point on `batch`: what about `batch` returning the `out` chan to be consistent with some core.async functions such as `pipe`, `tap`, etc. 

Let me know if you'd like a PR for any of these.

**Comment by bsless** [comment]
Hi @jjttjj thanks for bringing this to my attention. Can you tell me which version did you check it with? I've done a round of bug fixes, tweaks and renaming.
My intention with batch is for it to be slightly more generic than just sequences, you should be able to accumulate into anything, including arrays, strings, or something else I did not come up with. In that sense, for your use case it would be better to put a transducer on the output channel which just `(filter seq)` or something similar.
Regarding returning a channel, I'm on the fence. I imagined `batch` being more similar to `pipeline` than `pipe`. Does this make sense? It would also lead to an explosion in arities if I want to support all the channel arguments.
Looking over the implementation now, it looks like it also has a bug when dealing with a stateful init value, I'll hold off a new release until I fix that and give you a chance to reply.

**Comment by jjttjj** [comment]
Thanks for the response!

I'm using the current version, `bsless/more.async {:mvn/version "0.0.4"}`

I only bring this up because I have my own core async utilities and was giving your library a shot and replaced my own batch function with yours and found these behaviors different. I definitely don't feel that strongly about any of these but it seemed worth bringing up. 

That does make sense about not returning the out channel on batch. And I understand the idea that it should be able to reduce something other than vectors/sequences, that's a cool feature.  I'm slightly less convinced on returning empty batches every batch period on no inputs being the best default. 

I'm hesitant to give too much pushback, of course this is just a utility library and your implementation is perfectly acceptable, additionally, the `filter` solution you propose would work perfectly. Just figured I'd share my thoughts while I'm here :)

This is what I mean:
```
(def in (chan))
(def out (chan))

(ma/batch in out 10 100)
;;; no inputs to in
(<!! out) ;; []
(<!! out) ;; []
(<!! out) ;; []
```

In my usages of batching I don't often want to do something when there is a lack of new input, and when I do I think I'd probably want that to be an explicit part of the consuming process (with `alts!`+`timeout` on the batched chan for example), or use something more in line with `periodically!`. I think I would feel the same even if I was reducing to a stateful value.

**Comment by bsless** [comment]
What you're saying does make sense. I need to give it some thought. Maybe there's more than one function hiding here and the implementations should be separate

**Comment by bsless** [comment]
You convinced me it's a bug and I think I fixed it. Please have a peek at the branch when convenient.
I'm rather unhappy with the solution. On one hand, reading Hoare's paper paid off. On the other hand, it's dense and hard to keep track of.
I'll also add test cases for it.

**Comment by jjttjj** [comment]
Thanks! I'll take a look at your new implementation and see if I notice anything that can be cleaned up.

**Comment by bsless** [comment]
I already noticed binding timeout can be taken out of the loop, heads up :)

**Comment by jjttjj** [comment]
Here's my first stab at it and some very rough cuts for what might become tests. Not that it's better than yours just another viewpoint for possible inspiration if you want :) 

```clojure
(defn batch!
  "Takes messages from in and batch them until reaching size or
  timeout ms, and puts them to out.
  Batches with reducing function rf into initial value init.
  If init is not supplied rf is called with zero args."
  ([in out size timeout rf close?]
   (batch! in out size timeout rf (rf) close?))
  ([in out size timeout rf init close?]
   (assert (pos? size))
   (a/go-loop [n 0
               xs init
               t (a/timeout timeout)]
     (a/alt!
       in ([v]
           (if (nil? v)
             (do
               (when (pos? n) (>! out xs))
               (when close? (a/close! out)))
             (let [nn  (unchecked-inc n)
                   nxs (rf xs v)]
               (if (= nn size)
                 (do (a/>! out nxs)
                     (recur 0 init (a/timeout timeout)))
                 (recur nn nxs t)))))
       t (if (pos? n)
           (do (a/>! out xs) (recur 0 init (a/timeout timeout)))
           (recur n xs (a/timeout timeout)))))))


(let [in (a/to-chan!! (range 10))
      out (chan 10)
      result (a/into [] out)]
  (batch! in out 5 1000 conj true)
  (= (<!! result) [[0 1 2 3 4] [5 6 7 8 9]]))

(let [in      (chan 10)
      out     (chan 10)
      results (atom [])
      batches 5
      timeout 5]
  (batch! in out 500 timeout conj true)
  (a/go-loop [x batches]
    (when (pos? x)
      (>! in 1)
      (<! (a/timeout timeout))
      (recur (dec x))))
  (go-loop []
    (when-some [x (<! out)]
      (swap! results conj x)
      (recur)))
  (<!! (a/timeout (+ 100 (* timeout batches))))
  (= @results (map vector (repeat batches 1))))
```

**Comment by bsless** [comment]
I might end up adapting your solution because it generates less bytecode (on top of being simpler), I'll see what I can hack from it

**Comment by bsless** [comment]
Pushed a refactored version based on a synthesis between our approaches (with attribution), let me know what you think.

**Comment by jjttjj** [comment]
Looks good to me, thanks!
